version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hieu
      MYSQL_DATABASE: docker_demo
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/docker_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hieu
    depends_on:
      - db
    networks:
      - default

volumes:
  db-data:

networks:
  default:
    driver: bridge